name: sundrift
description: "A feature-rich weather application with stunning visuals and comprehensive weather data."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.5
  iconsax: ^0.0.8
  flutter_svg: ^2.0.5
  shimmer: ^3.0.0
  lottie: ^3.3.1
  cached_network_image: ^3.2.3
  flutter_animate: ^4.1.1+1
  share_plus: ^10.1.4
  flutter_slidable: ^4.0.0
  bottom_sheet: ^4.0.4
  confetti: ^0.8.0

  # Maps
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

  # State Management
  get: ^4.6.5
  equatable: ^2.0.5

  # Network & API
  dio: ^5.1.2
  connectivity_plus: ^6.1.3
  http: ^1.0.0

  # Storage
  shared_preferences: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  permission_handler: ^12.0.0+1

  # Location
  geolocator: ^14.0.0
  geocoding: ^3.0.0

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.1.11
  device_info_plus: ^11.3.0
  package_info_plus: ^8.3.0
  flutter_dotenv: ^5.1.0
  logger: ^2.5.0
  timeago: ^3.4.0
  uuid: ^4.5.1

  # Animations
  flutter_staggered_animations: ^1.1.1
  simple_animations: ^5.0.0+3

  # Charts and Graphs
  fl_chart: ^0.71.0
  syncfusion_flutter_charts: ^29.1.38
  syncfusion_flutter_gauges: ^29.1.38
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.4
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.4
  hive_generator: ^2.0.0
  mockito: ^5.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/backgrounds/
    - assets/images/illustrations/
    - assets/images/logos/
    - assets/icons/weather/
    - assets/icons/navigation/
    - assets/icons/ui/
    - assets/animations/lottie/
    - assets/animations/rive/
    - assets/json/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logos/sundrift_logo.png"

flutter_native_splash:
  color: "#1E88E5"
  image: assets/images/logos/sundrift_splash.png
  android: true
  ios: true